theme: jekyll-theme-cayman
title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Portland files\\: documenting abusive behavior by Norman Matthew Insley.
